### ISSUE TITLE
Infrastructure Manager - Add metrics, and alerts to improve observability

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/infrastructure-manager#11]
**Description**

The infrastructure Manager should provide metrics to allow early issues detection. 

**Reasons**

Infrastructure Manager is a component that in the long run will be responsible for cluster creation. In case of a downtime the impact on Kyma Control Plane will be significant. We must prevent that by increasing the observability.

Acceptance criteria
- [x] [Add metrics proposed by Benajmin](https://github.com/kyma-project/infrastructure-manager/issues/11#issuecomment-1737272422)
  - [x] Gardener Cluster CR metrics
  - [x] Kubeconfig expiration metrics - #163
    - [x] should expose shootName
    - [x] DEV bump
    - [x] configure DEV plutono
-  ~To have alerting set in place that will fire [we also have to figure out when] (based on expiration metrics) metrics)~
  - [x] Contact SRE when metrics will be available on DEV 
- ~Track failed request to Gardener API-server to measure the failure rate (helps detecting Gardener interruptions)~
  - There is a separate issue https://github.com/kyma-project/infrastructure-manager/issues/138 
- [x] Delete kube-rbac-proxy still sidecar similar change done in https://github.com/kyma-project/compass-manager/pull/55/files - https://github.com/kyma-project/infrastructure-manager/pull/164
- [x] metrics should be still valid after pod restarts

**Comment by ebensom** [comment]
I think besides exposing the controller_runtime_* and _workqueue_ metrics coming with https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics for having insights on controller performance, these custom metrics could make sense:
 - overall reconciliation state of each Cluster CR (reflecting the `.status.state`) , could be a gauge metric having 1 values for the specific runtime (label) in specific state (label), see [`lifecycle_mgr_kyma_state` for reference](https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/metrics/metrics.go#L27-L30). Assumption here is that state would be Error if kubeconfig co9uldn't be obtained/rotated, and a condition would indicate the reason, or else there would be a `status.reason` field indicating the reason for the errors, otherwise it would indicate "Cluster state is ready".
 - `infrastructure_mgr_cluster_kubeconfig_expiry`: gauge metric exposing current kubeconfig expiry value in [epoch timestamp value format](https://www.unixtimestamp.com/) . We could have monitoring and alertign for missing, expired or close to expire kubeconfigs based on these time series when cross-correlating with `lifecycle_mgr_kyma_state` series

**Comment by Disper** [comment]
Please consider that the issues with the gardener connection should be visible on any of the graphs.

**Comment by Disper** [comment]
Forcing rotation will not show the proper metrics until #145 is fixed.

**Comment by Disper** [comment]
Issue for alerting creating (internal no. 5389)
