### ISSUE TITLE
Valid CRs statuses should be set when KIM's operations succeed or fail

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#193]
Proposed solution for `Runtime` CR:

Following Statuses will represent current state of provisioned Kyma runtime:

- "**Creating**" - Kyma runtime is in progress of creation
- "**Ready**" - Runtime is ready to use 
- "**Error**" - There was an error during Runtime operation, Runtime cannot be used
- "**Processing**" - Kyma runtime is in progress of update, 
- "**Deleting**" - Kyma Runtime is being deleted

Following conditions will be used to describe processing steps for Runtime CR

- **"Provisioned"** - Gardener Shoot CR for Runtime is exists and is reconciled without errors.
- **"KubeconfigReady"** - Kubeconfig data is loaded into the dedicated seecret
- **"Configured"** - Kyma Runtime is configured: correct cluster Role bindings are created for cluster administrators

For each condition can be in following reasons may occur: 

-  Provisioned:
   - Initialised
   - Pending
   - ShootCreationCompleted
   - Processing
   - ProcessingCompleted

- Configured
   - ConfigurationStarted
   - ConfigurationCompleted

**Comment by tobiscr** [comment]
Just as proposal:

could we stay with the status closer to the commong statuses used for Pods (e.g. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase):

|Runtime status before|Runtime status proposed|Comment|
|--|--|--|
|Creating|Pending|Runtime currently processed|
|Ready|Running|Runtime is provisioned and running|
|Error|Failed|Runtime could not be provisioned|
|Processing|Pending|Runtime currently processed|
|Deleting|Terminating|Not an official state in K8s but used by `kubectl` and it's meaningful to have a clear indication when a Runtime is on the way to be deleted|

**Comment by koala7659** [comment]
Agree with one exception. We think that still "Ready" is better word than "Running" since we are preparing Runtime to be used by its users. 

Final table: 

|Suggested runtime status|Proposed status (=common pod phase)|Comment|
|--|--|--|
|Creating|Pending|Runtime currently processed|
|Ready|Ready|Runtime is provisioned and ready to use|
|Error|Failed|Runtime could not be provisioned|
|Processing|Pending|Runtime currently processed|
|Deleting|Terminating|`Terminating` is not an official phase of a K8s pod but used by `kubectl` and it's meaningful to have a clear indication when a Runtime is on the way to be deleted|

**Comment by PK85** [comment]
@Disper please provide CR yaml examples with those new status and values

**Comment by koala7659** [comment]
```
  status:
    conditions:
    - lastTransitionTime: "2024-06-24T07:34:30Z"
      message: Shoot creation in progress
      reason: Pending
      status: Unknown
      type: Provisioned
    state: Pending

```

**Comment by Disper** [comment]
@PK85 I've sent you some Runtime CRs examples via Slack

**Comment by tobiscr** [comment]
Implemented by @koala7659  - please create sub-issue if anything is missing!
