### ISSUE TITLE
KIM should create clusters for all hyperscalers 

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#206]
**Description**

KIM should react on newly created Runtime CRs, and apply Shoot resources on Gardener cluster.

AC:
- [x] KIM is able to produce working Shoot-Specs for AWS, Azure, GCP, and SAP Converged Cloud
- [x] Shoot-Spec is tested with Gardener and a Kubernetes cluster was successfully provisioned by Gardener
- [x] Automated tests are implemented which verify the generate Shoot-Specs with a provided Shoot-Spec template
- ~Consider if `shoot.Spec.Provider.Workers[]` should be migrated or always defaulted by KIM    - migrating that will assure that we will not trigger any change on gardener side~ - AC was from the time we wanted to have more rigid defaults but later we decided that we will rely on KEB.

**Comment by akgalwas** [comment]
Workplan
- [ ] [Implement MVP](https://github.com/kyma-project/infrastructure-manager/issues/215)
- [ ] Implement remaining converter features:
  - [ ] Annotation extender
  - [ ] Certificates extender (please see [this code](https://github.com/kyma-project/control-plane/blob/bc0d8345b6b4d47f52ceb7f05f98b953bcb8d73e/components/provisioner/internal/model/gardener_config.go#L213))
- [ ] Converters hardening:
  - [ ] DNS extender must not use deprecated  API
  - [ ] Hyperscaler specific config packages should import Gardener types instead of using code copied from Provisioner
